apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbmonedas-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  persistentVolumeReclaimPolicy: Delete